---
title: "Replication of Study "Tracking the relation between gist and item memory over the course of long-term memory consolidation" by Tima Zeng et al. (2021, eLife)"
author: "Chattarin Poungtubtim (cpoungtubtim@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

The reason I chose this paper to replicate is that I want to investiage the connection between the rate of representational drift in hippocampus and  the transition from detailed episodic memory to more abstract gist-like memory. In this paper, they studied how the spatial memory of locations became more attracted to the gist or an average of all location over time. Here I would to use this as an behavioral experiment and combine it with neuroimaging technique such as fMRI to track how neural representation of spatial memories correlate with gist-like transformation of the memory.

The stimuli used in this study will be black dot presented on the screen. Each dot is corresponded to a name of different places such as hospital, school. The dot will be presented sequentially and location of each of them will be different on the screen. So participants need to remember the match between the dot location and the place it represents e.g. A hospital is a dot located on the upper right. The training phase will let participants to learn an association between the location and name of the place. Then they will have to go over multiple testing phases : at 1 day, 1 week and 1 month after the training phase. For each test trials, participants will be showned a dot of on screen and the name of a place. Then they will need to answer the location and the name are correctly matched. On some trials, they will be asked to report an average location of all dots they learned during the training phase. Here, I plan to replicate experiment 1 in this study

The experiment will be built using jsPsych. Data will be collected through SONA system and participants need to perform a task on-site. There will be 4 sessions in total: learning task, memory task 1 day, 1 week and 1 month after learning. If the data collection could not be done in time, I might decide to collect data for memory task right after partcipants learned the location-place mapping. Then I will collect more data for memory tasks 3 days and 7 days after learning. I plan to recruit 60 participants for the initial learning session just in case participants drop out half way through the experiment. My plan for analysis to exclude any participants who do not show up at the memory task session 1 week after the learning.

Link to the paper : https://github.com/CP-PP8/Zeng2021/blob/main/original_paper/elife-65588-v3.pdf
Link to the repository : https://github.com/CP-PP8/Zeng2021/tree/main





## Methods


### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

60 subjects from UCSD psychology undergraduate students
tentative exclusion criteria
=> bad performance (high error, slow RT)
=> drop out of any session from 1 day - 1 week after the learning task

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
